chiirz/src/Entity/Itinerary.php
<?php

namespace App\Entity;

use App\Repository\ItineraryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ItineraryRepository::class)]
class Itinerary
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    private ?int $price = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $distance = null;

    #[ORM\ManyToOne(inversedBy: 'itineraries')]
    #[ORM\JoinColumn(nullable: false)]
    private ?City $fk_city = null;

    #[ORM\OneToMany(mappedBy: 'fk_itinerary', targetEntity: Like::class)]
    private Collection $likes;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $text = null;

    #[ORM\Column(nullable: true)]
    private ?array $bar = [];

    #[ORM\ManyToOne(inversedBy: 'itineraries')]
    private ?User $fk_user = null;

    #[ORM\Column(nullable: true)]
    private ?int $views = null;

    public function __construct()
    {
        $this->likes = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDistance(): ?string
    {
        return $this->distance;
    }

    public function setDistance(?string $distance): self
    {
        $this->distance = $distance;

        return $this;
    }

    public function getFkCity(): ?City
    {
        return $this->fk_city;
    }

    public function setFkCity(?City $fk_city): self
    {
        $this->fk_city = $fk_city;

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setFkItinerary($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getFkItinerary() === $this) {
                $like->setFkItinerary(null);
            }
        }

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getBar(): array
    {
        return $this->bar;
    }

    public function setBar(?array $bar): self
    {
        $this->bar = $bar;

        return $this;
    }

    public function getFkUser(): ?User
    {
        return $this->fk_user;
    }

    public function setFkUser(?User $fk_user): self
    {
        $this->fk_user = $fk_user;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(?int $views): self
    {
        $this->views = $views;

        return $this;
    }
}

chiirz/src/Form/ItineraryType.php
<?php

namespace App\Form;

use App\Entity\Itinerary;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Range;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;


class ItineraryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('fk_city')
            ->add('text', null, [
                'attr' => [
                    'placeholder' => '🎤 Un petit mot ? ',
                    'required' => true
                ]
            ])
            ->add('name', null, [
                'attr' => [
                    'placeholder' => 'Nom de la route',
                    'required' => true,
                    'maxlength' => 24
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Itinerary::class,
        ]);
    }
}

chiirz/src/Controller/ItineraryController.php
<?php

namespace App\Controller;

use App\Entity\Itinerary;
use App\Entity\City;
use App\Form\ItineraryType;
use App\Repository\ItineraryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\SecurityTrait;


#[Route('/itinerary')]
class ItineraryController extends AbstractController
{
    #[Route('/', name: 'app_itinerary_index', methods: ['GET'])]
    public function index(ItineraryRepository $itineraryRepository): Response
    {
        if (!$this->isGranted('IS_AUTHENTICATED_FULLY')) {
            throw new AccessDeniedException('You must be logged in to access this page.');
        }
        
        return $this->render('itinerary/index.html.twig', [
            'itineraries' => $itineraryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_itinerary_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ItineraryRepository $itineraryRepository): Response
    {
        if (!$this->isGranted('IS_AUTHENTICATED_FULLY')) {
            throw new AccessDeniedException('You must be logged in to access this page.');
        }

        $itinerary = new Itinerary();
        $form = $this->createForm(ItineraryType::class, $itinerary);
        $form->handleRequest($request);



        if ($form->isSubmitted() && $form->isValid()) {
            $itineraryRepository->save($itinerary, true);

            return $this->redirectToRoute('app_itinerary_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('itinerary/new.html.twig', [
            'itinerary' => $itinerary,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_itinerary_show', methods: ['GET'])]
    public function show(Itinerary $itinerary, EntityManagerInterface $entityManager): Response
    {

        // $students = $this->getDoctrine() 
        // ->getRepository('AppBundle:Student') 
        // ->findAll();  
        
        // if ($request->isXmlHttpRequest() || $request->query->get('showJson') == 1) {  
        // $jsonData = array();  
        // $idx = 0;  
        // foreach($students as $student) {  
        //     $temp = array(
        //         'name' => $student->getName(),  
        //         'address' => $student->getAddress(),  
        //     );   
        //     $jsonData[$idx++] = $temp;  
        // } 
        // return new JsonResponse($jsonData); 
        // } else { 
        // return $this->render('student/ajax.html.twig'); 
        // } 

        $itinerary->setViews($itinerary->getViews() + 1);

        $entityManager->persist($itinerary);
        $entityManager->flush();
        
        
        return $this->render('itinerary/show.html.twig', [
            'itinerary' => $itinerary,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_itinerary_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Itinerary $itinerary, ItineraryRepository $itineraryRepository): Response
    {
        $form = $this->createForm(ItineraryType::class, $itinerary);
        $form->handleRequest($request);

       /** @var User $user */
       $user = $this->getUser();
       if (!empty($user)) {
           $userId = $user->getId();
           // Your logic here...
       } else {
           throw new AccessDeniedException('You must be logged in to access this page.');
       }

        if (!$this->isGranted('ROLE_ADMIN') && $itinerary->getFkUser()->getId() == $userId) {
            throw new AccessDeniedException('You must be logged in to access this page.');
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $itineraryRepository->save($itinerary, true);

            return $this->redirectToRoute('app_itinerary_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('itinerary/edit.html.twig', [
            'itinerary' => $itinerary,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_itinerary_delete', methods: ['POST'])]
    public function delete(Request $request, Itinerary $itinerary, ItineraryRepository $itineraryRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$itinerary->getId(), $request->request->get('_token'))) {
            $itineraryRepository->remove($itinerary, true);
        }

        return $this->redirectToRoute('app_itinerary_index', [], Response::HTTP_SEE_OTHER);
    }

    // #[Route('/{id}/show', name: 'app_itinerary_showbyid', methods: ['POST'])]
    // public function showByCity(Request $request, Itinerary $itinerary, ItineraryRepository $itineraryRepository): Response
    // {
    //     return $this->render('itinerary/show.html.twig', [
    //         'itinerary' => $itinerary,
    //     ]);
    // }

    // #[Route('/showbycity/{id}', name: 'app_itinerary_showbyid', methods: ['GET'])]
    // public function showByCity(Itinerary $itinerary, EntityManagerInterface $entityManager): Response
    // {
    //     $id = $itinerary->getId();
        
    //     $itineraryRepository = $entityManager->getRepository(Itinerary::class);
    //     dump($itinerary->getFkCity()->getId());
    //     // Recupere les itineraires de la ville
    //     $itineraries = $itineraryRepository->createQueryBuilder('i')
    //         ->where('i.fk_city  = :id')
    //         ->setParameter('id', $id)
    //         ->getQuery()
    //         ->getResult();

    //     return $this->render('itinerary/index.html.twig', [
    //         'itineraries' => $itineraries,
    //     ]);
    // }
}

chiirz/templates/itinerary/_delete_form.html.twig
<form method="post" action="{{ path('app_itinerary_delete', {'id': itinerary.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ itinerary.id) }}">
    <button class="btn btn--delete">Supprimer</button>
</form>

chiirz/templates/itinerary/_form.html.twig
{# ************************* Header de la page #}
<header class="header-new">
        <div>
            <h1 class="title title--h1"> Créer une route de la soif sur </h1>
            {{ form_widget(form.fk_city) }}
        </div>
        
    <div class="header-new__img-container">
        <img src="{{ asset('img/monster.png') }}" alt="">
    </div>
</header>

{# ************************* API MAPS #}
<span data-user="{{ app.user.id }}" data-city="{{ asset('img/cityRandom.jpg') }}" data-link="{{asset('img/svg/location.svg')}}" data-pin="{{ asset('img/beer_border.png') }}" id="linkToPosImg" aria-hidden="true" style="display: none;"></span>

{# <li class='new__bar-input__prop__list__item'>
    <div class='new__bar-input__prop__list__item__name'>
        " + name + "
    </div>
    <div class='new__bar-input__prop__list__item__address'>
        <img src='" + linkToPosImg + "' alt=''>
        <div>
            " + locationArray[i] + "
        </div>
        <div class='new__bar-input__prop__list__item__address__add'>+</div>
    </div>
</li> #}

{# ************************* Section #}
<section class="new">
    <div class="new__map" id="newMap" height="200" width="200"></div>
    <div class="new__content">
        <div class="new__content__name">
            <label class="title title--h4" for="itinerary_name">Nom de la route de la soif</label>
            {{ form_widget(form.name) }}
        </div>
        
        <div class="new__content__bar-input">
            <label class="title title--h4" for="barNameInput">Ajouter un bar</label>
            <div class="new__content__bar-input__prop">
                <input class="new__content__bar-input__prop__search" type="text" name="bar-input" id="barNameInput" required="required" placeholder="🔍">
                <ul class="new__content__bar-input__prop__list" id="barList">
                </ul>
            </div>
        </div>

        <div class="new__content__step">
            <h3 class="title title--h4"> Étapes de la route de la <span> soif </span> </h3>
            <ul class="new__content__step__list" id="barStepList">
                {# <li class="new__content__step__list__item">
                    <div class="new__content__step__list__item__bar">
                        <div class="new__content__step__list__item__bar__step"></div>
                        <div class="new__content__step__list__item__bar__name"></div>
                    </div>
                    <div>
                        <button class="p p--16" id="deleteBarBtn">Supprimer</button>
                    </div>
                </li> #}
            </ul>
        </div>

        <div class="new__content__text">
            <label class="title title--h4" for="itinerary_text">Description</label>
            {{ form_widget(form.text) }}
        </div>
        
        <p class="new__content__distance">Distance totale : <span id="newDistance">0.0 km</span></p>
        <button class="btn btn--primary" id="sendBtn">{{ button_label|default('Terminer') }}</button>
    </div>
</section>

chiirz/templates/itinerary/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier {{itinerary.name}}{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/updateItinerary.js') }}" defer></script>
    <script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTF1YkHLhu-ami5vuu4x0HyQ1Zhrirq0Q&callback=initMap&libraries=places"></script>
{% endblock %}

{% block body %}
    <span style="display : none" id="itineraryId" data-id="{{itinerary.id}}"></span>
    {{ include('itinerary/_form.html.twig', {'button_label': 'Terminer les modifications'}) }}
{% endblock %}

chiirz/templates/itinerary/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Itinerary index{% endblock %}

{% block body %}

        <div class="user__favorite user__favorite--created">
            <h1 class="title title--h2">Mes routes de la soif</h1>
            <a href="{{ path('app_itinerary_new') }}" class="btn btn--primary">Créer une nouvelle route</a>
            {% for itinerary in itineraries %}
                {% if itinerary.fkUser.id == app.user.id %}
                    <a class="user__favorite__itiner-container__card" href="{{ path('app_itinerary_show', {'id': itinerary.id}) }}">
                        <img class="user__favorite__itiner-container__card__img-bar" src="{{ itinerary.bar['steps'][0]['img'][0] }}" alt="{{ itinerary.name }}"/>
                        <div class="user__favorite__itiner-container__card__desc">
                            <h3 class="title title--h4">{{ itinerary.name }}</h3>
                            <div class="user__favorite__itiner-container__card__row p p--16">
                                <div>{{ itinerary.bar.numberOfSteps }} Étapes</div>
                                <div class="user__favorite__itiner-container__card__row__rate">
                                    <img src="{{ asset('img/svg/star.svg') }}" alt="☆">
                                    <div>
                                        {% if itinerary.views != null %}
                                            {{ itinerary.views }}
                                        {% else %}
                                            0
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="user__favorite__itiner-container__card__row">
                                <div>{{ itinerary.distance }}</div>
                                <div class="user__favorite__itiner-container__card__row__views">
                                    <img src="{{ asset('img/svg/views.svg') }}" alt="vue">
                                    <div>
                                        {% if itinerary.views != null %}
                                            {{ itinerary.views }}
                                        {% else %}
                                            0
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endif %}
            {% endfor %}
        </div>
{% endblock %}

chiirz/templates/itinerary/new.html.twig
{% extends 'base.html.twig' %}
{% if not app.user %}
    {% do app.request.redirect('/') %}
{% endif %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/newItinerary.js') }}" defer></script>
    <script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTF1YkHLhu-ami5vuu4x0HyQ1Zhrirq0Q&callback=initMap&libraries=places"></script>
{% endblock %}

{% block title %}Nouvelle route{% endblock %}

{% block body %}

    {{ include('itinerary/_form.html.twig') }}

    
{% endblock %}

chiirz/templates/itinerary/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ itinerary.name }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/splide.css') }}" rel="stylesheet">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/splide.min.js') }}" defer></script>
    <script>
        const starImage = "{{ asset('img/svg/star.svg') }}";
    </script>
    <script src="{{ asset('js/itinerary.js') }}" defer></script>
    <script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTF1YkHLhu-ami5vuu4x0HyQ1Zhrirq0Q&callback=initMap&libraries=places"></script>
{% endblock %}

{% block body %}
    <section class="section-itinerary" {% if app.user %} data-user="{{ itinerary.fkUser.id }}" data-itinerary="{{ itinerary.id }}" id="dataset" {% endif %}>
        <div class="section-itinerary__maps" id="itineraryMap" data-city="{{ itinerary.fkCity.id }}">
            {# Intégration Google Maps #}
        </div>
        
        <div class="section-itinerary__content">
            <div class="section-itinerary__content__creator">
                <img src="{{ asset('img/glowing-star.png') }}" alt="☆">
                <p>Route de la soif imaginé par <a href="{{ path('user', { 'id': itinerary.fkuser.id }) }}" class="section-itinerary__content__creator__link">{{ itinerary.fkuser.pseudo }}</a></p>
            </div>
            <h1 class="title title--h2">{{ itinerary.name }}</h1>
            {% if app.user and (is_granted('ROLE_ADMIN') or app.user.id == itinerary.fkUser.id) %}
                <div class="section-itinerary__content__admin">
                    {{ include('itinerary/_delete_form.html.twig') }}
                    <a href="{{ path('app_itinerary_edit', {'id': itinerary.id }) }}" class="btn">Modifier</a>
                </div>
            {% endif %}
            <div class="section-itinerary__content__rate">
                <div class="section-itinerary__content__rate__rating">
                    <img src="{{ asset('img/svg/star.svg') }}" alt="☆">
                    <div>
                        {{ itinerary.bar['avgRate'] }}
                    </div>
                </div>
                <div class="section-itinerary__content__rate__views">
                    <img src="{{ asset('img/svg/views.svg') }}" alt="vue">
                    <div>
                    {% if itinerary.views != null %}
                        {{ itinerary.views }}
                    {% else %}
                        0
                    {% endif %}
                    </div>
                </div>
            </div>
            {% if itinerary.text is not empty %}
                <p class="section-itinerary__content__paragraph">{{ itinerary.text }}</p>
            {% endif %}

            <div class="section-itinerary__content__buttons">
                <a href="#parcours" class="section-itinerary__content__buttons__btn btn btn--primary-bis">
                    <div>C'est parti !</div>
                    <img src="{{ asset('img/tongue-smiley.png') }}" alt="😝">
                </a>
                <a href="" id="linkGoogleMap" target="__blank" class="section-itinerary__content__buttons__btn btn btn--secondary-bis">
                    <div>Ouvrir sur Google Maps</div>
                    <img src="{{ asset('img/svg/external_links.svg') }}" alt="↗">
                </a>
            </div>
            {% set haveLiked = false %}
            {% for like in itinerary.likes %}
                {% if like.fkUser.id == app.user.id %}
                    {% set haveLiked = true %}
                    <div class="section-itinerary__content__like fav--active" data-state="0" data-id="{{ like.id }}" id="favParent">
                        <img src="{{ asset('img/heart.png') }}" alt="♡" id="addTofavorites">
                        <div id="addToFavorites">Supprimer des favoris</div>
                    </div>
                {% endif %}
            {% endfor %}
            {% if haveLiked == false %}
                <div class="section-itinerary__content__like" data-state="1" data-id="" id="favParent">
                    <img src="{{ asset('img/heart.png') }}" alt="♡" id="addToFavorites">
                    <div id="addToFavorites">Ajouter aux favoris</div>
                </div>
            {% endif %}
            <div class="section-itinerary__content__steps">
                <h3 class="title title--h4">{{ itinerary.bar['numberOfSteps'] }}{# {{ itinerary.bar.numberOfSteps }} #} Étapes</h3>
                <ol>
                    {% for s in itinerary.bar['steps'] %}
                        <li> <span> {{loop.index}}. </span>{{ s.name }}</li>
                    {% endfor %}
                </ol>
            </div>
            <p class="section-itinerary__content__distance">Longeur du parcours : <span class="section-itinerary__content__distance__number">{{ itinerary.distance }}</p>
        </div>
    </section>


    {# //////////////////////////////PARCOURS/////////////////////////// #}
    <section class="section-parcours" id="parcours">
        <div class="section-parcours__progress-bar">
        </div>
 
        <div id="carouselSteps" class="splide section-parcours__big-splide">
            <div class="splide__track">
                <ul class="splide__list">
                    {% for s in itinerary.bar['steps'] %}
                        <li class="splide__slide">
                            <div class="section-parcours__content" >
                                <div class="section-parcours__content__splide splide" aria-label="Images de : {{ s['name'] }}" id="splidePics">
                                    <div class="splide__track">
                                        <ul class="splide__list">
                                            {% for img in s['img'] %}
                                                <li class="splide__slide"><img src="{{ img }}" alt="{{ s['name'] }}"></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                {# Repart à 0 sur la notation bem sinon trop long #}
                                <div class="parcours-info divContent">
                                    <div class="parcours-info__length" id="parcoursLength">
                                        
                                    </div>
                                    {# Nombre d'étape #}
                                    <div class="parcours-info__step-index">
                                        <p class="newDistance"></p>
                                        <p  class="title title--h2 "> Étape <span>{{ loop.index }}</span> <span class="parcours-info__step-index__of stepIndex">/{{ itinerary.bar['numberOfSteps'] }}</span> </p>
                                    </div>
                                    <a href="#" class="parcours-info__name stepName">
                                        <h3 class="title title--h4">
                                            {{ s['name'] }}
                                        </h3>
                                        <img src="{{ asset('img/svg/external_links.svg') }}" alt="">
                                    </a>
                                    {# Numéro de téléphone #}
                                    <a href="tel:" class="parcours-info__phone stepPhone"></a>
                                     <div class="parcours-info__rate" id="stepRate">
                                        <div class="parcours-info__rate__star">
                                            <img src="{{ asset('img/svg/star.svg') }}" alt="☆">
                                            {# Note moyenne du bar #}
                                            <div class="stepRateNumber"></div>
                                        </div>
                                        {# Nombre d'avis #}
                                        <div class="parcours-info__rate__opinion stepOpinion"></div>
                                    </div>
                                    
                                    {# <div class="parcours-info__price" id="stepPrice">{{itinerary.bar["avgPrice"]}}</div> #}
                                    <div class="parcours-info__opening">
                                        {# Info Ouvert ou fermé et heure d'ouverture Ouvert ● Lundi : 18h00-23h00 #}
                                        <p class="parcours-info__rate__opening__tag stepIsOpen"></p>
                                    </div>
                                    {# <div class="parcours-info__container-com">
                                        <div class="parcours-info__container-com__item">
                                            <div class="parcours-info__container-com__item__head">
                                                <div class="parcours-info__container-com__item__head__name" id="commentName"></div>
                                                <div class="parcours-info__container-com__item__head__rate" id="commentDate">
                                                    <img src="{{ asset('img/svg/star_color.svg') }}" alt="☆" data-index="{{ loop.index }}">
                                                    <img src="{{ asset('img/svg/star_color.svg') }}" alt="☆" data-index="{{ loop.index }}">
                                                    <img src="{{ asset('img/svg/star_color.svg') }}" alt="☆" data-index="{{ loop.index }}">
                                                    <img src="{{ asset('img/svg/star_color.svg') }}" alt="☆" data-index="{{ loop.index }}">
                                                    <img src="{{ asset('img/svg/star_color.svg') }}" alt="☆" data-index="{{ loop.index }}">
                                                </div>
                                            </div>
                                        </div>
                                    </div> #}
                                    
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>

    {# Test google API #}
    <div id="carte" height="200" width="200"></div>
{% endblock %}