chiirz/src/Entity/Like.php
<?php

namespace App\Entity;

use App\Repository\LikeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LikeRepository::class)]
#[ORM\Table(name: '`like`')]
class Like
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'likes')]
    private ?Itinerary $fk_itinerary = null;

    #[ORM\ManyToOne(inversedBy: 'likes')]
    private ?User $fk_user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFkItinerary(): ?Itinerary
    {
        return $this->fk_itinerary;
    }

    public function setFkItinerary(?Itinerary $fk_itinerary): self
    {
        $this->fk_itinerary = $fk_itinerary;

        return $this;
    }

    public function getFkUser(): ?User
    {
        return $this->fk_user;
    }

    public function setFkUser(?User $fk_user): self
    {
        $this->fk_user = $fk_user;

        return $this;
    }
}

chiirz/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $pseudo = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToMany(mappedBy: 'fk_user', targetEntity: Like::class)]
    private Collection $likes;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?City $fk_city = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $registered = null;

    #[ORM\OneToMany(mappedBy: 'fk_user', targetEntity: Itinerary::class)]
    private Collection $itineraries;

    public function __construct()
    {
        $this->likes = new ArrayCollection();
        $this->itineraries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setFkUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getFkUser() === $this) {
                $like->setFkUser(null);
            }
        }

        return $this;
    }

    public function getFkCity(): ?City
    {
        return $this->fk_city;
    }

    public function setFkCity(?City $fk_city): self
    {
        $this->fk_city = $fk_city;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRegistered(): ?\DateTimeInterface
    {
        return $this->registered;
    }

    public function setRegistered(\DateTimeInterface $registered): self
    {
        $this->registered = $registered;

        return $this;
    }

    /**
     * @return Collection<int, Itinerary>
     */
    public function getItineraries(): Collection
    {
        return $this->itineraries;
    }

    public function addItinerary(Itinerary $itinerary): self
    {
        if (!$this->itineraries->contains($itinerary)) {
            $this->itineraries->add($itinerary);
            $itinerary->setFkUser($this);
        }

        return $this;
    }

    public function removeItinerary(Itinerary $itinerary): self
    {
        if ($this->itineraries->removeElement($itinerary)) {
            // set the owning side to null (unless already changed)
            if ($itinerary->getFkUser() === $this) {
                $itinerary->setFkUser(null);
            }
        }

        return $this;
    }
}

chiirz/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('pseudo', null, ['label' => 'Pseudo'])
            ->add('fk_city', null, ['label' => 'Ma ville'])
            // ->add('img', FileType::class, [
            //     'label' => 'Image (fichier image)',
            //     'required' => false,
            //     'constraints' => [
            //         new File([
            //             'maxSize' => '1024k',
            //             'mimeTypes' => [
            //                 'image/*',
            //             ],
            //             'mimeTypesMessage' => 'Please upload a valid image',
            //         ])
            //     ],
            //     'data_class' => null,
            // ])
            ->add('email', EmailType::class, ['label' => 'E-mail'])
            ->add('password', null, ['label' => 'Mot de passe'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

chiirz/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

			$user->setRoles(['ROLE_USER']);
			$user->setRegistered(new DateTime('now'));
            $user->setPassword($passwordEncoder->encodePassword($user, $user->getPassword()));
            $userRepository->save($user, true);
            

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

chiirz/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button>Supprimer mon profil</button>
</form>

chiirz/templates/user/_form.html.twig
<div class="form__container-row">
    <div class="form__container-row__row">
        {{ form_errors(form.pseudo) }}
        {{ form_label(form.pseudo) }}
        {{ form_widget(form.pseudo, {'attr': {'class': 'form__row__item form__row__item--select'}})}}
    </div>
    <div class="form__container-row__row">
        {{ form_errors(form.fk_city) }}
        {{ form_label(form.fk_city) }}
        {{ form_widget(form.fk_city, {'attr': {'class': 'form__row__item form__row__item--select'}})}}
    </div>
</div>
<div class="form__row">
    {{ form_errors(form.email) }}
    {{ form_label(form.email) }}
    {{ form_widget(form.email, {'attr': {'class': 'form__row__item form__row__item--select'}})}}
</div>
<div class="form__row">
    {{ form_errors(form.password) }}
    {{ form_label(form.password) }}
    {{ form_widget(form.password, {'attr': {'class': 'form__row__item form__row__item--select'}})}}
</div>
<button class="btn btn--primary">{{ button_label|default('Inscription') }}</button>
    

{# {{ form_start(form) }}
{{ form_end(form) }} #}

chiirz/templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    {% if app.user %}
        <script defer>
            window.open('/user/{{ app.user.id }}', '_self');
        </script>
    {% else %}
        <section class="register">
            <div class="register__content">
                <h1 class="title title--h2">Rejoins nous ! </h1>
                {{ include('user/_form.html.twig') }}
            </div>
            <img src="{{ asset('img/smile-smiley.png')}}" alt="">
        </section>
    {% endif %} 
{% endblock %}

chiirz/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <section class="user">
        <header class="user__header">
            <div class="user__header__heading">
                <img src="{{ asset('img/confetti.png') }}" alt="">
                <div class="title title--h3">Profil du fêtard</div>
            </div>
            <div class="user__header__profil">
                <img src="{{ asset('img/login-smiley.png') }}" alt="{{ user.pseudo }}" class="user__header__user">
                <h3 class="title title--h3">{{ user.pseudo }}</h3>
                {% if app.user.id == user.id %}
                    <a href="{{ path('app_user_edit', {'id': user.id}) }}" class="user__header__alter">Modifier mon profil</a>
                {% endif %}
            </div>
            <div class="user__header__register-date">
                Membre depuis le <span> {{ user.registered | date('d/m/20y', 'Europe/Paris',  'fr_FR')}} </span>
            </div>
            <div class="user__header__city">
                <img src="{{ asset('img/city-night.png') }}" alt="">
                <div class="user__header__city__text">
                    <div class="user__header__city__text user__header__city__text--comrad">Camarade de</div>
                    <div class="user__header__city__text user__header__city__text--city">{{ user.fkCity.name }}</div>
                </div>
            </div>
            <div class="user__header__btn">
                <a href="{{ path('app_itinerary_new') }}" class="btn btn--primary">Créer une route de la soif</a>
                <a href="{{ path('city_from_user', {'id': user.fkCity.id}) }}" class="btn btn--secondary">Trouver une route</a>
            </div>

            <div class="user__header__logout-delete">
                {% if app.user.id == user.id or is_granted('ROLE_ADMIN') %}
                {{ include('user/_delete_form.html.twig') }}
                {% if app.user.id == user.id %}
                    <a href="{{ path('logout') }}" class="user__header__logout-delete__alter">Deconnexion</a>
                {% endif %}
            {% endif %}

            </div>
            
        </header>

        <div class="user__favorite">
            <h2 class="title title--h3">Routes de la soif favorites </h2>
            {% for l in user.likes %}
                <a class="user__favorite__itiner-container__card" href="{{ path('app_itinerary_show', {'id': l.fkItinerary.id}) }}">
                    <img class="user__favorite__itiner-container__card__img-bar" src="{{ l.fkItinerary.bar['steps'][0]['img'][0] }}" alt="{{ l.fkItinerary.name }}"/>
                    <div class="user__favorite__itiner-container__card__desc">
                        <h3 class="title title--h4">{{ l.fkItinerary.name }}</h3>
                        <div class="user__favorite__itiner-container__card__row p p--16">
                            <div>{{ l.fkItinerary.bar.numberOfSteps }} Étapes</div>
                            <div class="user__favorite__itiner-container__card__row__rate">
                                <img src="{{ asset('img/svg/star.svg') }}" alt="☆">
                                <div>
                                    {% if l.fkItinerary.views != null %}
                                        {{ l.fkItinerary.views }}
                                    {% else %}
                                        0
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="user__favorite__itiner-container__card__row">
                            <div>{{ l.fkItinerary.distance }}</div>
                            <div class="user__favorite__itiner-container__card__row__views">
                                {% if l.fkItinerary.views != null %}
                                    {{ l.fkItinerary.views }}
                                {% else %}
                                    0
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </section>

{% endblock %}